### ISSUE TITLE
Incorrect Character desplay

### ISSUE THREAD

**Issue by SpartanJoe193** [South-Paw/typeface-vag-rounded#1]
![image](https://user-images.githubusercontent.com/123623814/219823317-22e46f1a-dfa1-4c59-bed0-ae32877fd647.png)

**Comment by SpartanJoe193** [comment]
Ditto

![image](https://user-images.githubusercontent.com/123623814/219823354-20d2ea69-150c-4d4c-9265-482a97e136bb.png)

**Comment by South-Paw** [comment]
I didn't make the font files, just bundled them into a package
